version: 2.1
orbs:
  flutter: circleci/flutter@2.0.2
jobs:
  build-and-test:
    docker:
      - image: cimg/flutter:stable
    steps:
      - checkout
      - flutter/install_sdk:
          version: stable
      - flutter/install_pub
      - run:
          name: Flutter analyze
          command: flutter analyze
      - run:
          name: Run Flutter tests
          command: flutter test
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test