version: 2.1
orbs:
  flutter: circleci/flutter@2.0.2
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    executor: docker
    steps:
      - checkout
      - flutter/install_sdk:
          version: stable
      - flutter/install_pub
      - run:
          name: Run Flutter tests
          command: flutter test

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test