version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:stable
    steps:
      - checkout
      - run:
          name: Flutter version
          command: flutter --version
      - run:
          name: Run tests
          command: flutter test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build